baseurl = "https://justinribeiro.com/"
languageCode = "en-us"
title = "Justin Ribeiro"

# specifcally for the PWA and GAE to load and parse
publishdir = "../app/data"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  chronicle = "/chronicle/:year/:month/:day/:slug/"

[params]
  ISO8601 = "2006-01-02T15:04:05PST"

[sitemap]
  changefreq = "weekly"
  priority = 0.5